using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Template.Hotfix.Analyzer
{
    /// <summary>
    /// 往它所应用到的程序集里写一个探针类型，用来回答「源生成器的产物能不能落进热更程序集」。
    /// 探针里带着宿主程序集名，取到什么名字就证明产物落在了哪个程序集内。
    /// </summary>
    [Generator]
    public sealed class HotfixProbeGenerator : IIncrementalGenerator
    {
        private const string GeneratedFileName = "HotfixSourceGeneratorProbe.g.cs";
        private const string UnnamedAssembly = "未命名程序集";

        /// <summary>注册生成步骤：每个程序集编译一次，产出一个探针类型。</summary>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var assemblyNames = context.CompilationProvider.Select(
                static (compilation, _) => compilation.AssemblyName ?? UnnamedAssembly);

            context.RegisterSourceOutput(assemblyNames, static (sourceProductionContext, assemblyName) =>
            {
                sourceProductionContext.AddSource(
                    GeneratedFileName,
                    SourceText.From(BuildProbeSource(assemblyName), Encoding.UTF8));
            });
        }

        private static string BuildProbeSource(string assemblyName)
        {
            return @"// <auto-generated />
namespace Template.Hotfix.Generated
{
    /// <summary>源生成器写进来的探针。运行期反射取得到它，就说明生成物随程序集一起走完了整条链路。</summary>
    public static class HotfixSourceGeneratorProbe
    {
        /// <summary>产物所在的程序集名，由源生成器在编译期写死。</summary>
        public const string HostAssemblyName = """ + assemblyName + @""";

        /// <summary>返回一行可打印的自述，供出包验收比对。</summary>
        public static string Describe()
        {
            return ""源生成器产物 · 宿主程序集 "" + HostAssemblyName;
        }
    }
}
";
        }
    }
}
