// <auto-generated>
//     本文件由 codegen 从 Config/Schema/技能.schema.json 生成，手工改动会在下次生成时丢失。
// </auto-generated>
using System.Collections.Generic;

namespace Template.Logic.Data.Generated
{
    /// <summary>配置表「技能」的一行。</summary>
    public sealed class SkillRow
    {
        /// <summary>编号。</summary>
        public int SkillId { get; set; }

        /// <summary>全局编号。</summary>
        public long GlobalSkillId { get; set; }

        /// <summary>技能名称。</summary>
        public string SkillName { get; set; }

        /// <summary>冷却秒数。</summary>
        public float CooldownSeconds { get; set; }

        /// <summary>是否被动。</summary>
        public bool IsPassive { get; set; }
    }

    /// <summary>配置表「技能」的访问入口，按主键查行。</summary>
    public sealed class SkillTable
    {
        private readonly Dictionary<int, SkillRow> _rowsByPrimaryKey = new Dictionary<int, SkillRow>();

        /// <summary>全部行。</summary>
        public IReadOnlyCollection<SkillRow> Rows => _rowsByPrimaryKey.Values;

        /// <summary>按主键取一行，取不到返回 null。</summary>
        public SkillRow Find(int skillId)
        {
            return _rowsByPrimaryKey.TryGetValue(skillId, out var row) ? row : null;
        }

        /// <summary>装入一行，主键重复时覆盖。</summary>
        public void Add(SkillRow row)
        {
            _rowsByPrimaryKey[row.SkillId] = row;
        }
    }
}
