using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Text;
using Template.Toolkit.ConfigBridge;

namespace Template.Toolkit.CodeGen
{
    /// <summary>配置表管线的 Luban 实现：Excel ↔ 镜像仍走 ConfigBridge，访问代码与运行时数据交给 Luban 生成。</summary>
    /// <remarks>
    /// 与 <see cref="ScribanTablePipeline"/> 的分工：Excel ↔ 镜像这一段是本仓库自己的（Luban 没有回写 Excel 的能力，
    /// 而回写正是本模板的关键能力之一），所以那三个成员原样委托给 <see cref="ConfigSyncService"/>；
    /// 生成访问代码与导出运行时数据则交给 Luban 的命令行工具，schema 由 <see cref="LubanDefinitionWriter"/> 投影成 defines。
    /// </remarks>
    public sealed class LubanTablePipeline : ITablePipeline
    {
        private readonly ConfigSyncService _configSyncService;
        private readonly string _templateRoot;
        private readonly string _workingDirectory;
        private readonly string _lubanToolPath;
        private readonly string _codeOutputDirectory;
        private readonly string _dataOutputDirectory;

        /// <summary>用模板根目录构造。</summary>
        /// <param name="templateRoot">模板根目录。</param>
        public LubanTablePipeline(string templateRoot)
        {
            _templateRoot = templateRoot;
            _configSyncService = new ConfigSyncService(Path.Combine(templateRoot, "Config"));

            // 工作目录落在 Temp/Luban：Luban 生成的 .cs 是带 <auto-generated> 头、无中文摘要的第三方产物，
            // 过不了本仓库的命名门禁，也不该进版本库。Temp/ 既被 .gitignore 忽略，也被门禁扫描跳过，
            // defines 与 conf 又是每次生成时重写的一次性投影，正好归进这里。
            _workingDirectory = Path.Combine(templateRoot, "Temp", "Luban");
            _lubanToolPath = Path.Combine(templateRoot, "Tools", "Luban", "Luban.dll");
            _codeOutputDirectory = Path.Combine(_workingDirectory, "Generated", "Code");
            _dataOutputDirectory = Path.Combine(_workingDirectory, "Generated", "Data");
        }

        /// <summary>管线实现的名字，返回 "Luban"。</summary>
        public string PipelineName => "Luban";

        /// <summary>Excel → 镜像 JSON。</summary>
        /// <param name="tableName">表名。</param>
        public ConfigOperationResult SyncFromWorkbook(string tableName)
        {
            return _configSyncService.Sync(tableName);
        }

        /// <summary>镜像 JSON → Excel。</summary>
        /// <param name="tableName">表名。</param>
        public ConfigOperationResult ApplyToWorkbook(string tableName)
        {
            return _configSyncService.Apply(tableName);
        }

        /// <summary>按 schema 校验镜像内容。</summary>
        /// <param name="tableName">表名。</param>
        public ConfigOperationResult Validate(string tableName)
        {
            return _configSyncService.Validate(tableName);
        }

        /// <summary>从 schema 生成 Luban defines，跑 cs-simple-json code target，返回这张表的 bean 与 table 两个 .cs 文件路径。</summary>
        /// <param name="tableName">表名。</param>
        public IReadOnlyList<string> GenerateAccessCode(string tableName)
        {
            var schema = LoadSchema(tableName);
            LubanDefinitionWriter.Write(_templateRoot, _workingDirectory);
            RunLuban("cs-simple-json", _codeOutputDirectory);

            var beanPath = Path.Combine(_codeOutputDirectory, schema.TableIdentifierName + ".cs");
            var tablePath = Path.Combine(_codeOutputDirectory, LubanDefinitionWriter.TableNameOf(schema) + ".cs");
            return new[] { beanPath, tablePath };
        }

        /// <summary>跑 Luban 的 json data target，返回这张表的运行时数据文件路径。</summary>
        /// <param name="tableName">表名。</param>
        public IReadOnlyList<string> ExportRuntimeData(string tableName)
        {
            var schema = LoadSchema(tableName);
            LubanDefinitionWriter.Write(_templateRoot, _workingDirectory);
            RunLuban("json", _dataOutputDirectory);

            var dataPath = Path.Combine(
                _dataOutputDirectory,
                LubanDefinitionWriter.TableNameOf(schema).ToLowerInvariant() + ".json");
            return new[] { dataPath };
        }

        private TableSchema LoadSchema(string tableName)
        {
            var schemaPath = Path.Combine(_templateRoot, "Config", "Schema", tableName + ".schema.json");
            if (!File.Exists(schemaPath))
            {
                throw new InvalidOperationException(
                    $"位置：{schemaPath}；原因：schema 文件不存在；修复：核对表名；参考：Config/Schema 目录。");
            }

            return SchemaLoader.LoadFromFile(schemaPath);
        }

        private void RunLuban(string targetName, string outputDirectory)
        {
            if (!File.Exists(_lubanToolPath))
            {
                throw new InvalidOperationException(
                    $"位置：{_lubanToolPath}；原因：Luban 可执行文件缺失；" +
                    "修复：跑 Tools/Luban/取工具.ps1 现取；参考：Tools/Luban/来源说明.md。");
            }

            // 模板根可能是相对路径（命令层传的就是相对路径），而进程工作目录与命令宿主不同，
            // 所以工具、conf、输出目录一律先归一成绝对路径，避免相对路径被套在错误的基准目录上。
            var workingDirectory = Path.GetFullPath(_workingDirectory);
            var lubanToolPath = Path.GetFullPath(_lubanToolPath);
            var configurationPath = Path.GetFullPath(Path.Combine(_workingDirectory, "luban.conf"));
            var fullOutputDirectory = Path.GetFullPath(outputDirectory);
            Directory.CreateDirectory(fullOutputDirectory);

            var outputArgument = targetName == "json" ? "json.outputDataDir" : "cs-simple-json.outputCodeDir";
            var relativeOutput = Path.GetRelativePath(workingDirectory, fullOutputDirectory).Replace('\\', '/');
            var targetFlag = targetName == "json" ? "-d" : "-c";
            var arguments = $"\"{lubanToolPath}\" -t all {targetFlag} {targetName} --conf \"{configurationPath}\" -x {outputArgument}={relativeOutput}";

            var startInfo = new ProcessStartInfo
            {
                FileName = "dotnet",
                Arguments = arguments,
                WorkingDirectory = workingDirectory,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                StandardOutputEncoding = Encoding.UTF8,
                StandardErrorEncoding = Encoding.UTF8
            };

            using var process = new Process { StartInfo = startInfo };
            process.Start();

            // Luban 输出量小（几十行日志），顺序读两个流不会填满缓冲区造成死锁。
            var stdout = process.StandardOutput.ReadToEnd();
            var stderr = process.StandardError.ReadToEnd();
            process.WaitForExit();

            if (process.ExitCode != 0)
            {
                var tail = (stdout + stderr).Trim();
                if (tail.Length > 2000)
                {
                    tail = tail.Substring(tail.Length - 2000);
                }

                throw new InvalidOperationException(
                    $"位置：{configurationPath}；原因：Luban 生成失败，退出码 {process.ExitCode}；" +
                    $"修复：看参考里的 Luban 输出定位；参考：{tail}");
            }
        }
    }
}
