// <auto-generated>
//     本文件由 codegen 从 Config/Schema/背包.schema.json 生成，手工改动会在下次生成时丢失。
// </auto-generated>
using System.Collections.Generic;

namespace Template.Shared.Data.Generated
{
    /// <summary>配置表「背包」的一行。</summary>
    public sealed class BagRow
    {
        /// <summary>编号。</summary>
        public int ItemId { get; set; }

        /// <summary>名称。</summary>
        public string ItemName { get; set; }

        /// <summary>堆叠上限。</summary>
        public int StackLimit { get; set; }

        /// <summary>售价。</summary>
        public int SellPrice { get; set; }
    }

    /// <summary>配置表「背包」的访问入口，按主键查行。</summary>
    public sealed class BagTable
    {
        private readonly Dictionary<int, BagRow> _rowsByPrimaryKey = new Dictionary<int, BagRow>();

        /// <summary>全部行。</summary>
        public IReadOnlyCollection<BagRow> Rows => _rowsByPrimaryKey.Values;

        /// <summary>按主键取一行，取不到返回 null。</summary>
        public BagRow Find(int itemId)
        {
            return _rowsByPrimaryKey.TryGetValue(itemId, out var row) ? row : null;
        }

        /// <summary>装入一行，主键重复时覆盖。</summary>
        public void Add(BagRow row)
        {
            _rowsByPrimaryKey[row.ItemId] = row;
        }
    }
}
