// <auto-generated>
//     本文件由 codegen 从 Config/Schema/Monster.schema.json 生成，手工改动会在下次生成时丢失。
// </auto-generated>
using System.Collections.Generic;

namespace Template.Shared.Data.Generated
{
    /// <summary>配置表「怪物」的一行。</summary>
    public sealed class MonsterRow
    {
        /// <summary>关卡编号。</summary>
        public int LevelId { get; set; }

        /// <summary>怪物编号。</summary>
        public int MonsterId { get; set; }

        /// <summary>怪物名称。</summary>
        public string MonsterName { get; set; }

        /// <summary>生命值。</summary>
        public int HealthPoint { get; set; }

        /// <summary>是否精英。</summary>
        public bool IsElite { get; set; }
    }

    /// <summary>配置表「怪物」的访问入口，主键多于一个，按「关卡编号|怪物编号」的顺序把各主键值用 | 拼成复合键查行。</summary>
    public sealed class MonsterTable
    {
        private readonly Dictionary<string, MonsterRow> _rowsByCompositeKey = new Dictionary<string, MonsterRow>();

        /// <summary>全部行。</summary>
        public IReadOnlyCollection<MonsterRow> Rows => _rowsByCompositeKey.Values;

        /// <summary>按复合主键取一行，取不到返回 null。键由各主键值按「关卡编号|怪物编号」顺序拼接。</summary>
        public MonsterRow Find(int levelId, int monsterId)
        {
            return _rowsByCompositeKey.TryGetValue(levelId + "|" + monsterId, out var row) ? row : null;
        }

        /// <summary>装入一行，主键重复时覆盖。</summary>
        public void Add(MonsterRow row)
        {
            _rowsByCompositeKey[row.LevelId + "|" + row.MonsterId] = row;
        }
    }
}
