// <auto-generated>
//     本文件由 ui.scaffold 从 UI/Definitions/主界面.uidef.json 生成，手工改动会在下次生成时丢失。
// </auto-generated>
using HSGFrame.UiFramework;
using UnityEngine.UIElements;

namespace Template.View.Generated
{
    /// <summary>面板「主界面」的骨架，业务逻辑写在另一个 partial 文件里。</summary>
    /// <remarks>
    /// 骨架自带 <c>PanelBase</c> 基类与 OnOpen / OnClose 的落地实现，所以**不写业务 partial 也编得过**——
    /// 生成物落在 Game.View 里跟着工程一起编译，编不过的骨架会把整个程序集带崩。
    /// 业务逻辑走 <c>OnPanelOpened</c> / <c>OnPanelClosed</c> 这两个 partial 方法：
    /// 在自己的 partial 文件里实现就生效，不实现则由编译器整段抹掉，零成本。
    /// </remarks>
    public partial class MainPanel : PanelBase
    {
        /// <summary>本面板所在的层。</summary>
        public override PanelLayer Layer => PanelLayer.Normal;

        /// <summary>元素「血条」。</summary>
        public ProgressBar HealthBar { get; private set; }

        /// <summary>元素「金币文本」。</summary>
        public Label CoinText { get; private set; }

        /// <summary>元素「背包按钮」。</summary>
        public Button InventoryButton { get; private set; }

        /// <summary>面板打开时：先把元素绑定好，再交给业务侧的 OnPanelOpened。</summary>
        public override void OnOpen()
        {
            BindElements(Root);
            OnPanelOpened();
        }

        /// <summary>面板关闭时：交给业务侧的 OnPanelClosed。</summary>
        public override void OnClose()
        {
            OnPanelClosed();
        }

        /// <summary>按标识名从视觉树上取出全部元素，供面板打开时调用一次。</summary>
        /// <remarks>元素树可以嵌套，这里摊平成一维——<c>Q</c> 按标识名跨层级查，与嵌套深度无关。</remarks>
        public void BindElements(VisualElement root)
        {
            HealthBar = root.Q<ProgressBar>("HealthBar");
            CoinText = root.Q<Label>("CoinText");
            InventoryButton = root.Q<Button>("InventoryButton");
        }

        /// <summary>业务侧的打开回调，在自己的 partial 文件里实现。</summary>
        partial void OnPanelOpened();

        /// <summary>业务侧的关闭回调，在自己的 partial 文件里实现。</summary>
        partial void OnPanelClosed();
    }
}
